kind: Deployment
apiVersion: apps/v1
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goproxy
  template:
    metadata:
      labels:
        app: goproxy
    spec:
      containers:
      - name: goproxy
        image: registry.cn-hangzhou.aliyuncs.com/shenkonghui/goproxy
        ports:
          - name: socks
            containerPort: 38080
      tolerations:
      - effect: NoSchedule
        key: harm.cn/type
        operator: Equal
        value: active-active
---
kind: Service
apiVersion: v1
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  type: NodePort
  selector:
    app: goproxy
  ports:
  - name: socks
    port: 38080
    nodePort: 30080
